# Generated by Django 5.0.1 on 2024-02-14 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='county',
            new_name='country',
        ),
    ]
